// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdowPagElQKdqaY1vGS5Mn-TAhJWIf7Cc',
    appId: '1:701084073854:web:6fa2899c66187183807d2f',
    messagingSenderId: '701084073854',
    projectId: 'mymy-easy-tutorial',
    authDomain: 'mymy-easy-tutorial.firebaseapp.com',
    storageBucket: 'mymy-easy-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMHFZPcBtlwsdm85xFBuTQhKndGu3dw0',
    appId: '1:701084073854:android:dd1266121a6c0421807d2f',
    messagingSenderId: '701084073854',
    projectId: 'mymy-easy-tutorial',
    storageBucket: 'mymy-easy-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONKg-K09-kZpcl4pLOeDQ0Kyy8PBQo1k',
    appId: '1:701084073854:ios:25fa503735338880807d2f',
    messagingSenderId: '701084073854',
    projectId: 'mymy-easy-tutorial',
    storageBucket: 'mymy-easy-tutorial.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONKg-K09-kZpcl4pLOeDQ0Kyy8PBQo1k',
    appId: '1:701084073854:ios:25fa503735338880807d2f',
    messagingSenderId: '701084073854',
    projectId: 'mymy-easy-tutorial',
    storageBucket: 'mymy-easy-tutorial.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdowPagElQKdqaY1vGS5Mn-TAhJWIf7Cc',
    appId: '1:701084073854:web:5b3df6b8d3136105807d2f',
    messagingSenderId: '701084073854',
    projectId: 'mymy-easy-tutorial',
    authDomain: 'mymy-easy-tutorial.firebaseapp.com',
    storageBucket: 'mymy-easy-tutorial.firebasestorage.app',
  );
}
